name: Label Issues (Script Injection)

on:
  issues:
    types:
        - opened

jobs:
    assign-lebel:
        runs-on : ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            
            - name: Add a Level
              env:
                AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              run: |
                issue_title="${{github.event.issue_title}}"
                if [[ "$issue_title" == *"bug"* ]]; then
                    echo "Issue is about a bug!"
                    echo  "Assinging Label - BUG...................."
                else
                    echo "Not a bug"
                fi